d-o-p-e/time-machine-letter

front/public/global.css
front/src/components/WriteLetter.js
front/src/css/Main.module.css
front/src/index.js
front/src/pages/Main.js

사진에서는 보이지 않지만 X버튼 흰색으로 추가하였습니다

[CA-8] 편지 작성페이지 UI개발

---

front/public/global.css
front/src/components/LetterList.js
front/src/css/Main.module.css
front/src/index.js
front/src/pages/Main.js

[CA-7] 메인페이지 UI 개발

---

back/build.gradle
back/src/main/java/crappyUnivLife/timeMachineLetter/api/MemberApiController.java
back/src/main/java/crappyUnivLife/timeMachineLetter/domain/Member.java
back/src/main/java/crappyUnivLife/timeMachineLetter/dto/KakaoUserInfo.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/LetterRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/MemberRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/security/kakao/KakaoOAuth2.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/LetterService.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/MemberService.java
back/src/main/resources/application.yml

카카오 소셜 로그인 기능 구현.
세션쿠키를 통한 로그인 유지.

[Ca-1] 카카오 로그인 기능 구현

---

back/src/main/java/crappyUnivLife/timeMachineLetter/config/WebConfig.java
back/src/main/java/crappyUnivLife/timeMachineLetter/security/kakao/KakaoOAuth2.java
back/src/main/resources/application.yml

[CA-14] CORS 문제 해결

---

back/src/main/java/crappyUnivLife/timeMachineLetter/config/WebConfig.java

[Re][CA-14] CORS 문제 해결

---

back/src/main/java/crappyUnivLife/timeMachineLetter/api/MemberApiController.java
back/src/main/java/crappyUnivLife/timeMachineLetter/dto/PostListResponse.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/MemberService.java

이제 로그인 시, 편지 리스트를 response로 받을 수 있습니다.
아직 dummy data 로, null 값만 들어가있는 상태입니다.

[CA-14] 로그인 API 편지 리스트 response.

---

back/src/main/java/crappyUnivLife/timeMachineLetter/config/WebConfig.java

쿠키 활용을 위한 Access-Control-Allow-Credentials 문제 해결

[CA-15] Access-Control-Allow-Credentials 문제 해결

---

back/.gitignore
back/build.gradle
back/src/main/java/crappyUnivLife/timeMachineLetter/api/MemberApiController.java
back/src/main/java/crappyUnivLife/timeMachineLetter/domain/Letter.java
back/src/main/java/crappyUnivLife/timeMachineLetter/domain/Member.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/LetterRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/MemberRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/LetterService.java
back/src/test/java/crappyUnivLife/timeMachineLetter/repository/LetterRepositoryTest.java
back/src/test/resources/application.yml

post: URL/letter
로그인 세션 확인 후 작성.
테스트 코드 추가 완료.

[CA-2] 편지 작성 API

---

back/src/main/java/crappyUnivLife/timeMachineLetter/api/MemberApiController.java
back/src/main/java/crappyUnivLife/timeMachineLetter/dto/PostListResponse.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/LetterRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/MemberRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/LetterService.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/MemberService.java
back/src/test/java/crappyUnivLife/timeMachineLetter/repository/LetterRepositoryTest.java
back/src/test/java/crappyUnivLife/timeMachineLetter/service/LetterServiceTest.java

로그인 후 메인에서 편지 리스트를 가져오는 API 작성
GET : URL/letter

[CA-4] 편지 리스트 가져오기 API

---

front/src/components/LetterLoading.js
front/src/components/LetterView.js
front/src/pages/Letter.js
front/src/pages/Routers.js

1. dummy date를 이용한 체크
2. loading창에서 password와 hash params를 이용해서 다시 post요청을 보내도록 수정

[CA-22] 편지 읽기 전 password check 기능 추가

---

front/src/components/LetterDetail.js
front/src/components/LetterList.js
front/src/components/LetterPreviewModal.js
front/src/components/WriteLetter.js
front/src/pages/Main.js
front/src/store/global.js

1. modal 컴포넌트 main으로 위치변경
2. 편지 수정 modal 추가
3. hash 전역 state 추가

[CA-23] 편지 수정 페이지 추가

---

front/src/components/LetterDetail.js
front/src/components/LetterList.js
front/src/components/LetterView.js
front/src/components/WriteLetter.js
front/src/pages/KakaoHandler.js
front/src/pages/Main.js
front/src/service/Letter.js
front/src/service/login.js
front/src/store/auth.js
front/src/store/letter.js

[CA-20] 컴포넌트에 API추가

---

front/src/components/LetterDetail.js
front/src/components/LetterList.js
front/src/components/WriteLetter.js
front/src/pages/Main.js
front/src/store/auth.js

[CA-28] component 버그 수정

---

back/src/main/java/crappyUnivLife/timeMachineLetter/repository/LetterRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/repository/MemberRepository.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/LetterService.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/MemberService.java

getSingleResult()의 null pointer exception로 인한 문제 발생.
getSingleList() 이후 Optional 로 null값 해결.

[CA-31] 유저/게시글 조회 시 실패 에러 해결

---

back/src/main/java/crappyUnivLife/timeMachineLetter/api/MemberApiController.java
back/src/main/java/crappyUnivLife/timeMachineLetter/domain/Letter.java
back/src/main/java/crappyUnivLife/timeMachineLetter/dto/DecryptionLetterRequest.java
back/src/main/java/crappyUnivLife/timeMachineLetter/dto/LetterReadResponse.java
back/src/main/java/crappyUnivLife/timeMachineLetter/service/LetterService.java
back/src/test/java/crappyUnivLife/timeMachineLetter/service/LetterServiceTest.java
back/src/test/resources/application.yml

readable : 편지 open 시간 판단
isEncrypted : 편지 암호화 여부

[CA-25] 편지 읽는 조건 추가

---

front/src/pages/Main.js
front/src/pages/Routers.js

1. router 기능을 이용해 정보가 없을시 로그인 페이지로 이동 구현

:art: 메인화면 에서 로그인페이지로 이동 구조 수정

---

front/src/components/LetterDetail.js
front/src/components/LetterLoading.js
front/src/css/App.module.css
front/src/css/Main.module.css
front/src/pages/Letter.js
front/src/service/Letter.js

편지 URL과 접속시에 편지를 열람할수 있게 API를 추가하였음

[CA-29] 편지 열람 API연결

---

iOS/.gitignore
iOS/TimeMachineLetter.xcodeproj/project.pbxproj
iOS/TimeMachineLetter.xcodeproj/project.xcworkspace/contents.xcworkspacedata
iOS/TimeMachineLetter.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
iOS/TimeMachineLetter/AppDelegate.swift
iOS/TimeMachineLetter/Assets.xcassets/AccentColor.colorset/Contents.json
iOS/TimeMachineLetter/Assets.xcassets/AppIcon.appiconset/Contents.json
iOS/TimeMachineLetter/Assets.xcassets/Contents.json
iOS/TimeMachineLetter/Base.lproj/LaunchScreen.storyboard
iOS/TimeMachineLetter/Base.lproj/Main.storyboard
iOS/TimeMachineLetter/Info.plist
iOS/TimeMachineLetter/SceneDelegate.swift
iOS/TimeMachineLetter/ViewController.swift

🎉iOS 개발 환경 구축

---

front/package-lock.json
front/package.json
front/src/components/LetterList.js
front/src/components/WriteLetter.js

[CA-34] 편지 리스트 UI수정

---

front/package-lock.json
front/package.json
front/src/components/LetterDetail.js
front/src/components/LetterLoading.js
front/src/components/LetterUpdate.js
front/src/components/WriteLetter.js
front/src/utils/converter.js
front/src/utils/time.js

:truck: 컴포넌트에 정의 되어 있는 기능 함수 utils로 이동

---

front/.eslintrc
front/package-lock.json
front/package.json
front/src/__mocks__/react-redux.js
front/src/__test__/components/LetterList/LetterList.test.js
front/src/__test__/components/LetterList/LetterListCard.test.js
front/src/components/LetterDetail.js
front/src/components/LetterList/LetterList.js
front/src/components/LetterList/LetterListCard.js
front/src/components/LetterLoading.js
front/src/components/LetterUpdate.js
front/src/components/WriteLetter.js
front/src/fixtures/dummyLetter.js
front/src/setupTests.js
front/src/utils/converter.js
front/src/utils/time.js
front/test.utils.js

close #44
test코드 작성에 따른 component 분리가 있습니다
기존 LetterList파일 하나에서 폴더로 변경해 List와 Card로 분리하였습니다.
LetterList 테스트는 편지 openAt에 따라서 UI에 해당 옵션에 따른 편지를 필터링해서 보여주는지 테스트 하였습니다.
Card 테스트는 클릭시에 함수로 hash가 넘어가는 테스트를 하였습니다.
@JinuCheon 그냥 테스트코드 구경해보십셔~~

:white_check_mark: LetterList testcode 작성

---

iOS/TimeMachineLetter.xcodeproj/project.pbxproj
iOS/TimeMachineLetter/View/WritingLetterViewController.swift

편지 작성 페이지의 기본적인 UI를 구현하였습니다.
close #52

:lipstick:편지 작성페이지를 구현한다

---

iOS/TimeMachineLetter.xcodeproj/project.pbxproj
iOS/TimeMachineLetter/View/WritingLetterViewController.swift

편지작성 페이지의 UI를 수정하고 일부 기능을 추가했다.
close #56

:lipstick:편지작성 페이지의 기능을 추가한다.

---

iOS/TimeMachineLetter.xcodeproj/project.pbxproj
iOS/TimeMachineLetter/AppDelegate.swift
iOS/TimeMachineLetter/Info.plist
iOS/TimeMachineLetter/Model/KakaoLoginManager.swift
iOS/TimeMachineLetter/SceneDelegate.swift
iOS/TimeMachineLetter/View/LoginViewController.swift
iOS/TimeMachineLetter/View/WritingLetterViewController.swift

Model 폴더에 KakaoLoginManager 추가
로그인 성공시 페이지 변경, 실패시 알림창 팝업
close #50

✨카카오 로그인 구현

---

iOS/TimeMachineLetter.xcodeproj/project.pbxproj
iOS/TimeMachineLetter/Model/LetterManager.swift
iOS/TimeMachineLetter/Model/LetterModel.swift
iOS/TimeMachineLetter/View/WritingLetterViewController.swift

편지 작성 후 보내기 버튼 누를 시에 서버로 POST 요청
성공시 편지 작성 페이지 닫힘, 실패시 경고창 알림
close #60

✨편지 작성 페이지와 서버 연결

---

front/public/global.css
front/src/components/LetterList/LetterList.js
front/src/components/LetterList/LetterListCard.js
front/src/components/NavBar.js
front/src/css/Main.module.css
front/src/css/NavBar.module.css
front/src/pages/Main.js

style: Main UI변경

---

front/public/global.css
front/src/components/LetterDetail.js

:lipstick: LetterDetail UI 변경

---

front/public/global.css
front/src/components/LetterDetail.js
front/src/components/LetterWrite.js
front/src/pages/Main.js

:lipstick: LetterWrite UI 변경
